# Формат промпта (Отрезали жесткий текст стрелки и заменили на динамический модуль $character)
format = """
[👹 ONI-SYS](bold #ff2a5f) [::](bold #666666) $directory$git_branch$git_status
$character"""

# Отключаем перенос строки, чтобы экономить место в 70%-м окне Yakuake
add_newline = false

# Динамическая стрелочка Oni-Core (При успехе — красный, при ошибке — малиновый/фиолетовый)
[character]
success_symbol = "[> ](bold #ff2a5f)"
error_symbol = "[> ](bold #b82aff)"

[directory]
# Меням фиолетовый на пепельно-белый/светло-серый, чтобы папка читалась на красно-черном фоне
style = "bold #e0e0e0"
truncation_length = 3
truncate_to_repo = false
read_only = " 🔒"

[git_branch]
# Насыщенный темно-красный (кровавый) для веток Git
style = "bold #c62828"
symbol = " 🌿 "

[git_status]
# Формат отображения статуса репозитория
style = "bold #ff2a5f"
format = "([\\[$all_status$ahead_behind\\]]($style) )"
conflicted = "💥"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "❓"
stashed = "📦"
modified = "📝"
staged = "✅"
renamed = "🚚"
deleted = "🗑️"
